<div align="center">
<table border=12 cellpadding=12 cellspacing=6 bgcolor="white" bordercolor="black">
<tr>
<td bgcolor="black" align="center">
<font size=6 color="red"><b>* CLOSED *</b></font><p>
<font color="white">
Effective March 28, 2021, NHRC Repeater Controllers will cease all operations.<p>
We will honor all warranties and offer <i>limited</i> support by email for the remainder of the warranty period.<p>
We want to thank all our friends and customers for your support during our 22 year venture.<p>
Be safe, stay well.<p>
Peter KA1OKQ, and Jeff N1KDO.
</font>
</td>
</tr>
</table>
</div>
