<div>
<font size="2">
<?php
if ($version != "") {
echo $_SERVER['PHP_SELF'] . ", version $version, last modified " . date ("d F Y H:i", getlastmod()) . "<br>\n";
}
if ($copydate != "") {
echo "Copyright &#169; $copydate, NHRC LLC, all rights reserved.<br>";
}
?>
Mail comments to
<script language="javascript" type="text/javascript">
mto = "\155\x61\u0069\x6c\164\x6f\u003a"
addr = "\x77\x65\x62\u0040\156\150\162\143\u002e\156\145\164"
document.writeln('\x3ca href="'+mto+addr+'">'+addr+'\x3c/a>')
</script>
</font>
<br>
</div>
</body>
</html>
